export const TEMPLATES = {
  japan: {
    id: 'japan',
    name: 'Japan',
    flag: '🇯🇵',
    countryCode: 'JPN',
    countryName: 'JAPAN',
    type: 'P',
    titleLocal: '日本国',
    passportLabel: 'PASSPORT',
    bg: '#f5f0dc',
    bgGradient: 'linear-gradient(135deg, #f5f0dc 0%, #ede5c8 100%)',
    headerBg: 'transparent',
    accentColor: '#b8860b',
    accentLight: 'rgba(184,134,11,0.12)',
    headerTextColor: '#1a1a1a',
    borderColor: 'rgba(180,150,80,0.35)',
    mrzBg: 'rgba(0,0,0,0.04)',
    mrzBorder: 'rgba(0,0,0,0.15)',
    emblemColor: '#4a7c3f',
    cornerColor: '#b8860b',
    watermarkColor: 'rgba(184,134,11,0.08)',
    surnameLabel: '姓/Surname',
    givenNameLabel: '名/Given name',
    nationalityLabel: '国　籍/Nationality',
    dobLabel: '生年月日/Date of birth',
    sexLabel: '性別/Sex',
    domicileLabel: '本　籍/Registered Domicile',
    issueLabel: '交付年月日/Date of issue',
    expiryLabel: '有効期限満了日/Date of expiry',
    authorityLabel: '発行官庁/Authority',
    signatureLabel: '所持人自署/Signature of bearer',
    typeLabel: '型/Type',
    issuingLabel: '発行国/Issuing country',
    passNoLabel: '旅券番号/Passport No.',
  },

  chile: {
    id: 'chile',
    name: 'Chile',
    flag: '🇨🇱',
    countryCode: 'CHL',
    countryName: 'CHILE',
    type: 'P',
    titleLocal: 'REPÚBLICA DE CHILE',
    passportLabel: 'PASAPORTE / PASSPORT',
    bg: '#f0f4f8',
    bgGradient: 'linear-gradient(135deg, #f0f4f8 0%, #e6ecf2 100%)',
    accentColor: '#c8102e',
    accentLight: 'rgba(200,16,46,0.08)',
    headerTextColor: '#0d2d6e',
    borderColor: 'rgba(200,16,46,0.3)',
    mrzBg: 'rgba(13,45,110,0.05)',
    mrzBorder: 'rgba(13,45,110,0.2)',
    emblemColor: '#c8102e',
    cornerColor: '#0d2d6e',
    watermarkColor: 'rgba(13,45,110,0.06)',
    surnameLabel: 'Apellido/Surname',
    givenNameLabel: 'Nombre/Given name',
    nationalityLabel: 'Nacionalidad/Nationality',
    dobLabel: 'Fecha de Nac./Date of birth',
    sexLabel: 'Sexo/Sex',
    domicileLabel: 'Lugar Nac./Place of birth',
    issueLabel: 'Fecha Emisión/Date of issue',
    expiryLabel: 'Fecha Venc./Date of expiry',
    authorityLabel: 'Autoridad/Authority',
    signatureLabel: 'Firma/Signature',
    typeLabel: 'Tipo/Type',
    issuingLabel: 'País/Country',
    passNoLabel: 'N° Pasaporte/Passport No.',
  },

  indonesia: {
    id: 'indonesia',
    name: 'Indonesia',
    flag: '🇮🇩',
    countryCode: 'IDN',
    countryName: 'INDONESIA',
    type: 'P',
    titleLocal: 'REPUBLIK INDONESIA',
    passportLabel: 'PASPOR / PASSPORT',
    bg: '#fdf8f5',
    bgGradient: 'linear-gradient(135deg, #fdf8f5 0%, #f5ede6 100%)',
    accentColor: '#cc0001',
    accentLight: 'rgba(204,0,1,0.08)',
    headerTextColor: '#cc0001',
    borderColor: 'rgba(204,0,1,0.25)',
    mrzBg: 'rgba(204,0,1,0.04)',
    mrzBorder: 'rgba(204,0,1,0.2)',
    emblemColor: '#8b6914',
    cornerColor: '#cc0001',
    watermarkColor: 'rgba(204,0,1,0.06)',
    surnameLabel: 'Nama Keluarga/Surname',
    givenNameLabel: 'Nama/Given name',
    nationalityLabel: 'Kewarganegaraan/Nationality',
    dobLabel: 'Tgl. Lahir/Date of birth',
    sexLabel: 'Jenis Kelamin/Sex',
    domicileLabel: 'Tempat Lahir/Place of birth',
    issueLabel: 'Tgl. Penerbitan/Date of issue',
    expiryLabel: 'Tgl. Berakhir/Date of expiry',
    authorityLabel: 'Pejabat/Authority',
    signatureLabel: 'Tanda Tangan/Signature',
    typeLabel: 'Jenis/Type',
    issuingLabel: 'Negara Penerbit/Country',
    passNoLabel: 'No. Paspor/Passport No.',
  },

  algeria: {
    id: 'algeria',
    name: 'Algeria',
    flag: '🇩🇿',
    countryCode: 'DZA',
    countryName: 'ALGÉRIE / ALGERIA',
    type: 'P',
    titleLocal: 'الجمهورية الجزائرية',
    passportLabel: 'PASSEPORT / PASSPORT',
    bg: '#f4f9f4',
    bgGradient: 'linear-gradient(135deg, #f4f9f4 0%, #e8f4e8 100%)',
    accentColor: '#006233',
    accentLight: 'rgba(0,98,51,0.08)',
    headerTextColor: '#006233',
    borderColor: 'rgba(0,98,51,0.3)',
    mrzBg: 'rgba(0,98,51,0.04)',
    mrzBorder: 'rgba(0,98,51,0.2)',
    emblemColor: '#006233',
    cornerColor: '#c8102e',
    watermarkColor: 'rgba(0,98,51,0.06)',
    surnameLabel: 'Nom/Surname',
    givenNameLabel: 'Prénom/Given name',
    nationalityLabel: 'Nationalité/Nationality',
    dobLabel: 'Date de naissance/Date of birth',
    sexLabel: 'Sexe/Sex',
    domicileLabel: 'Lieu de naissance/Place of birth',
    issueLabel: 'Date de délivrance/Date of issue',
    expiryLabel: 'Date d\'expiration/Date of expiry',
    authorityLabel: 'Autorité/Authority',
    signatureLabel: 'Signature/Signature',
    typeLabel: 'Type/Type',
    issuingLabel: 'Pays/Country',
    passNoLabel: 'N° Passeport/Passport No.',
  },

  usa: {
    id: 'usa',
    name: 'United States',
    flag: '🇺🇸',
    countryCode: 'USA',
    countryName: 'UNITED STATES OF AMERICA',
    type: 'P',
    titleLocal: 'UNITED STATES OF AMERICA',
    passportLabel: 'PASSPORT',
    bg: '#f2f4f8',
    bgGradient: 'linear-gradient(135deg, #f2f4f8 0%, #e8ecf4 100%)',
    accentColor: '#002868',
    accentLight: 'rgba(0,40,104,0.08)',
    headerTextColor: '#002868',
    borderColor: 'rgba(0,40,104,0.25)',
    mrzBg: 'rgba(0,40,104,0.04)',
    mrzBorder: 'rgba(0,40,104,0.2)',
    emblemColor: '#b22234',
    cornerColor: '#002868',
    watermarkColor: 'rgba(0,40,104,0.06)',
    surnameLabel: 'Surname',
    givenNameLabel: 'Given Names',
    nationalityLabel: 'Nationality',
    dobLabel: 'Date of birth',
    sexLabel: 'Sex',
    domicileLabel: 'Place of birth',
    issueLabel: 'Date of issue',
    expiryLabel: 'Date of expiry',
    authorityLabel: 'Authority',
    signatureLabel: 'Signature',
    typeLabel: 'Type',
    issuingLabel: 'Country',
    passNoLabel: 'Passport No.',
  },

  france: {
    id: 'france',
    name: 'France',
    flag: '🇫🇷',
    countryCode: 'FRA',
    countryName: 'FRANCE',
    type: 'P',
    titleLocal: 'RÉPUBLIQUE FRANÇAISE',
    passportLabel: 'PASSEPORT / PASSPORT',
    bg: '#f5f5f8',
    bgGradient: 'linear-gradient(135deg, #f5f5f8 0%, #ebedf5 100%)',
    accentColor: '#002395',
    accentLight: 'rgba(0,35,149,0.08)',
    headerTextColor: '#002395',
    borderColor: 'rgba(0,35,149,0.25)',
    mrzBg: 'rgba(0,35,149,0.04)',
    mrzBorder: 'rgba(0,35,149,0.2)',
    emblemColor: '#ed2939',
    cornerColor: '#002395',
    watermarkColor: 'rgba(0,35,149,0.06)',
    surnameLabel: 'Nom/Surname',
    givenNameLabel: 'Prénoms/Given names',
    nationalityLabel: 'Nationalité/Nationality',
    dobLabel: 'Date de naissance/Date of birth',
    sexLabel: 'Sexe/Sex',
    domicileLabel: 'Lieu de naissance/Place of birth',
    issueLabel: 'Date de délivrance/Date of issue',
    expiryLabel: 'Date d\'expiration/Date of expiry',
    authorityLabel: 'Autorité/Authority',
    signatureLabel: 'Signature du titulaire',
    typeLabel: 'Type',
    issuingLabel: 'Pays/Country',
    passNoLabel: 'N° Passeport',
  },

  germany: {
    id: 'germany',
    name: 'Germany',
    flag: '🇩🇪',
    countryCode: 'DEU',
    countryName: 'DEUTSCHLAND / GERMANY',
    type: 'P',
    titleLocal: 'BUNDESREPUBLIK DEUTSCHLAND',
    passportLabel: 'REISEPASS / PASSPORT',
    bg: '#f8f8f6',
    bgGradient: 'linear-gradient(135deg, #f8f8f6 0%, #eeeee8 100%)',
    accentColor: '#000000',
    accentLight: 'rgba(0,0,0,0.06)',
    headerTextColor: '#111',
    borderColor: 'rgba(0,0,0,0.2)',
    mrzBg: 'rgba(0,0,0,0.04)',
    mrzBorder: 'rgba(0,0,0,0.18)',
    emblemColor: '#dd0000',
    cornerColor: '#dd0000',
    watermarkColor: 'rgba(221,0,0,0.05)',
    surnameLabel: 'Name/Surname',
    givenNameLabel: 'Vornamen/Given names',
    nationalityLabel: 'Staatsangeh./Nationality',
    dobLabel: 'Geburtsdatum/Date of birth',
    sexLabel: 'Geschlecht/Sex',
    domicileLabel: 'Geburtsort/Place of birth',
    issueLabel: 'Ausstellungsdatum/Date of issue',
    expiryLabel: 'Gültig bis/Date of expiry',
    authorityLabel: 'Ausstellende Behörde/Authority',
    signatureLabel: 'Unterschrift/Signature',
    typeLabel: 'Art/Type',
    issuingLabel: 'Staatsangeh./Country',
    passNoLabel: 'Seriennr./Passport No.',
  },

  brazil: {
    id: 'brazil',
    name: 'Brazil',
    flag: '🇧🇷',
    countryCode: 'BRA',
    countryName: 'BRASIL / BRAZIL',
    type: 'P',
    titleLocal: 'REPÚBLICA FEDERATIVA DO BRASIL',
    passportLabel: 'PASSAPORTE / PASSPORT',
    bg: '#f5fbf5',
    bgGradient: 'linear-gradient(135deg, #f5fbf5 0%, #eaf5ea 100%)',
    accentColor: '#009c3b',
    accentLight: 'rgba(0,156,59,0.08)',
    headerTextColor: '#002776',
    borderColor: 'rgba(0,156,59,0.3)',
    mrzBg: 'rgba(0,39,118,0.04)',
    mrzBorder: 'rgba(0,39,118,0.2)',
    emblemColor: '#009c3b',
    cornerColor: '#ffdf00',
    watermarkColor: 'rgba(0,156,59,0.06)',
    surnameLabel: 'Sobrenome/Surname',
    givenNameLabel: 'Nome/Given name',
    nationalityLabel: 'Nacionalidade/Nationality',
    dobLabel: 'Data de Nasc./Date of birth',
    sexLabel: 'Sexo/Sex',
    domicileLabel: 'Local de Nasc./Place of birth',
    issueLabel: 'Data de Emissão/Date of issue',
    expiryLabel: 'Data de Validade/Date of expiry',
    authorityLabel: 'Autoridade/Authority',
    signatureLabel: 'Assinatura/Signature',
    typeLabel: 'Tipo/Type',
    issuingLabel: 'País/Country',
    passNoLabel: 'Nº Passaporte/Passport No.',
  },

  uk: {
    id: 'uk',
    name: 'United Kingdom',
    flag: '🇬🇧',
    countryCode: 'GBR',
    countryName: 'UNITED KINGDOM',
    type: 'P',
    titleLocal: 'UNITED KINGDOM OF GREAT BRITAIN\nAND NORTHERN IRELAND',
    passportLabel: 'PASSPORT',
    bg: '#f5f3f8',
    bgGradient: 'linear-gradient(135deg, #f5f3f8 0%, #ede9f5 100%)',
    accentColor: '#012169',
    accentLight: 'rgba(1,33,105,0.08)',
    headerTextColor: '#012169',
    borderColor: 'rgba(1,33,105,0.25)',
    mrzBg: 'rgba(1,33,105,0.04)',
    mrzBorder: 'rgba(1,33,105,0.2)',
    emblemColor: '#c8102e',
    cornerColor: '#012169',
    watermarkColor: 'rgba(1,33,105,0.06)',
    surnameLabel: 'Surname',
    givenNameLabel: 'Given names',
    nationalityLabel: 'Nationality',
    dobLabel: 'Date of birth',
    sexLabel: 'Sex',
    domicileLabel: 'Place of birth',
    issueLabel: 'Date of issue',
    expiryLabel: 'Date of expiry',
    authorityLabel: 'Authority',
    signatureLabel: 'Signature of bearer',
    typeLabel: 'Type',
    issuingLabel: 'Country code',
    passNoLabel: 'Passport No.',
  },

  australia: {
    id: 'australia',
    name: 'Australia',
    flag: '🇦🇺',
    countryCode: 'AUS',
    countryName: 'AUSTRALIA',
    type: 'P',
    titleLocal: 'COMMONWEALTH OF AUSTRALIA',
    passportLabel: 'PASSPORT',
    bg: '#f3f7fb',
    bgGradient: 'linear-gradient(135deg, #f3f7fb 0%, #e8f0f8 100%)',
    accentColor: '#00008B',
    accentLight: 'rgba(0,0,139,0.07)',
    headerTextColor: '#00008B',
    borderColor: 'rgba(0,0,139,0.2)',
    mrzBg: 'rgba(0,0,139,0.04)',
    mrzBorder: 'rgba(0,0,139,0.18)',
    emblemColor: '#c8a800',
    cornerColor: '#00008B',
    watermarkColor: 'rgba(0,0,139,0.05)',
    surnameLabel: 'Surname',
    givenNameLabel: 'Given names',
    nationalityLabel: 'Nationality',
    dobLabel: 'Date of birth',
    sexLabel: 'Sex',
    domicileLabel: 'Place of birth',
    issueLabel: 'Date of issue',
    expiryLabel: 'Date of expiry',
    authorityLabel: 'Authority',
    signatureLabel: 'Signature of bearer',
    typeLabel: 'Type',
    issuingLabel: 'Country',
    passNoLabel: 'Passport No.',
  },
}

export function randomPassportNo() {
  const letters = 'ABCDEFGHJKLMNPQRSTUVWXYZ'
  const L1 = letters[Math.floor(Math.random() * letters.length)]
  const L2 = letters[Math.floor(Math.random() * letters.length)]
  const digits = Math.floor(Math.random() * 9000000 + 1000000)
  return `${L1}${L2}${digits}`
}
